name: automate cd pipeline

on:
  create:
   
    branches: [Distro]



jobs:
  
  job2:
   
    runs-on: ubuntu-latest

    steps:

      - name: Generate Version
        id: versioning
        uses: sceccotti89/Github-Action-Versioning@v1.0.5
    
      - name: Get the output version
        run: echo "Version = ${{ steps.versioning.outputs.version }}"
          
          

     

      
      - name: Trigger 1
        run: curl -X POST -u esraa:118bbe54e299d788977f0de867be41b495 http://196.219.234.11:8090//job/Backend-CD/job/branch2/build 
