name: automate ci pipeline

on:
  push:
   
    branches: [main]

env: 
  arr: ${{ null }}

jobs:
  
  job1:
   
    runs-on: ubuntu-latest

    steps:

      - name: Create Distro Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:  
          branch: 'Distro'

      - name: Trigger 1
        run: curl -X POST -u esraa:${{ secrets.MYTOKEN }} http://196.219.234.11:8090//job/Backed-CI/job/main/build 

           
  job3:
      needs: job1
      
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: hhhh
        run: git branch -r
      - name: access values
        run: |
          echo "TAG_NAME=$(git branch -r)" >> $GITHUB_OUTPUT

         
  
 
          

            
