name: automate ci pipeline

on:
  push:
   
    branches: [main]



jobs:
  
  job1:
   
    runs-on: ubuntu-latest

    steps:

      - name: Create Distro Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:  
          branch: 'Distro'
          
          

     

      
      - name: Trigger 1
        run: curl --connect-timeout 5 -X POST -u esraa:118bbe54e299d788977f0de867be41b495 http://192.168.1.178:8080/job/Backed-CI/job/main/build


 
          

            
