name: automate ci pipeline

on:
  push:
   
    branches: [main]


jobs:
  
  job1:
   
    runs-on: ubuntu-latest

    steps:

      - name: Create Distro Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:  
          branch: 'Distro'

      - name: Trigger 1
        run: curl -X POST -u esraa:${{ secrets.MYTOKEN }} http://196.219.234.11:8090//job/Backed-CI/job/main/build 
      - name: username
        run: whoami

           
  job3:
      needs: job1
      
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: hhhh
        run: git branch -r
      - name: getting user
        run: whoami
      - name: create directory
        run: |
          sudo mkdir /home/data1
          sudo touch /home/data1/text1
        

      - name: validate Distro branch exist
        run: |
           sudo git branch -r >> /home/data1/text1
           grep 'Distro'  /home/data1/text1 
           
      
      - name: Generate Version
        id: versioning
        uses: sceccotti89/Github-Action-Versioning@v1.0.5
        with:
            default-branch: 'Distro'
          
      - name: Get the output version
        run: |
            echo "Version = ${{ steps.versioning.outputs.version }}"
            echo "Distro version "
            git branch Distro
      - name: Taging
        uses: nimblehq/branch-tag-action@v1
        with:
          ref: Distro
      
 
          
  


    
          
        

         
  
 
          

            
