name: automate ci pipeline

on:
  push:
   
    branches: [main]


jobs:
  
  job1:
   
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: list branches
        run: git branch -r 
      - name: list tags
        run: git tag -n

      - name: Create Distro Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:  
          branch: 'Distro'

      - name: Trigger 1
        run: curl -X POST -u esraa:${{ secrets.MYTOKEN }} http://196.219.234.11:8090//job/Backed-CI/job/main/build 
      - name: username
        run: whoami

           
  job3:
      needs: job1
      
      runs-on: ubuntu-latest
      steps:
      
      - name: checkout repo
        uses: actions/checkout@v1
      - name: hhhh
        run: git branch -r
      - name: getting user
        run: whoami
      - name: create directory
        run: |
          sudo mkdir /home/data1
          sudo touch /home/data1/text1
        

      - name: validate Distro branch exist
        run: |
           sudo git branch -r >> /home/data1/text1
           grep 'Distro'  /home/data1/text1 
           
      
      - name: Create an incremental release
        run: |
          echo "List branches"
          git branch -r
          echo "Configure who ami"
          git config --global user.email "esraa.hassanien@aiactive.com"
          git config --global user.name "esraaelhasanen"
          echo "Switching to Distro"
          git checkout origin/Distro  
          git tag -a v.1.1 -m "trying to point to Distro"
          echo "listing"
          git tag -n 
          git branch
          git log --oneline
          echo "Trigger CD Pipeline"
          curl -X POST -u esraa:${{ secrets.MYTOKEN }} http://196.219.234.11:8090//job/Backend-CD/job/branch2/build 

       

 
          
  


    
          
        

         
  
 
          

            
