name: automate ci pipeline

on:
  push:
   
    branches: [main]



jobs:
  
  job1:
   
    runs-on: ubuntu-latest

    steps:

      - name: Create Distro Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:  
          branch: 'Distro'

      
      - name: Trigger 1
        run: java -jar jenkins-cli.jar -s ${{ secrets.JENKINS_URL }}  build BackEnd_Checkout -s -v

      - name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINSTOKEN }}
          JENKINS_HOST: ${{ secrets.JENKINS_URL }}
          JENKINS_JOB: "Backed-CI"


      - name: Trigger jenkins job2
        uses: jabbukka/jenkins-trigger@main
        with:
          url: ${{ secrets.JENKINS_URL }}       
          job_name: "BackEnd_Checkout"      
          user_name: ${{ secrets.JENKINS_USER }}    
          api_token: ${{ secrets.JENKINSTOKEN }}   
          

            
